server:
  port: 8080
  allow_host:
    - "*"

mongodb:
  url: "mongodb://localhost:27017/ganja"
  db: "ganja"

postgresql:
  host: localhost
  port: 5432
  user: postgres
  password: dongnguyenltqb
  db: test
